name: Deployment
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
env:
  MONGO_DB_NAME: gha-demo
jobs:
  test:
    env:
      MONGO_CLUSTER_ADDRESS: gha-demo.2r2f8.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: echo "http://127.0.0.1:${{ env.PORT }}"
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_PASSWORD: ${{ env.MONGODB_PASSWORD }}"
          echo "MONGO_DB_NAME: $MONGO_DB_NAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "MONGO_DB_NAME: $MONGO_DB_NAME"